from __future__ import annotations

from datetime import datetime
from typing import Any, Optional

from pydantic import BaseModel, ConfigDict, Field, field_validator

from app.database.models import (
    MEMORY_TYPES,
    ActionStatus,
    DEFAULT_MEMORY_TYPE,
    MessageStatus,
    TaskPriority,
    TaskStatus,
)

# ---------------------------------------------------------------- Messages


class MessageCreate(BaseModel):
    content: str = Field(min_length=1, max_length=8000)
    client_id: Optional[str] = Field(
        default=None,
        max_length=64,
        description="Optional idempotency key generated by the client (PWA offline queue).",
    )


class MessageOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    client_id: Optional[str]
    content: str
    status: MessageStatus
    response: Optional[str]
    error: Optional[str]
    created_at: datetime
    processed_at: Optional[datetime]


# ---------------------------------------------------------------- Tasks


class TaskCreate(BaseModel):
    title: str = Field(min_length=1, max_length=255)
    description: Optional[str] = None
    priority: TaskPriority = TaskPriority.medium
    due_at: Optional[datetime] = None


class TaskUpdate(BaseModel):
    title: Optional[str] = Field(default=None, min_length=1, max_length=255)
    description: Optional[str] = None
    status: Optional[TaskStatus] = None
    priority: Optional[TaskPriority] = None
    due_at: Optional[datetime] = None


class TaskOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    title: str
    description: Optional[str]
    status: TaskStatus
    priority: TaskPriority
    due_at: Optional[datetime]
    created_at: datetime
    completed_at: Optional[datetime]


# ---------------------------------------------------------------- Memory


class MemoryCreate(BaseModel):
    content: str = Field(min_length=1, max_length=4000)
    category: Optional[str] = Field(default=None, max_length=64)
    memory_type: str = Field(default=DEFAULT_MEMORY_TYPE, max_length=32)

    @field_validator("memory_type")
    @classmethod
    def _valid_memory_type(cls, v: str) -> str:
        if v not in MEMORY_TYPES:
            raise ValueError(f"memory_type must be one of {MEMORY_TYPES}")
        return v


class MemoryOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    content: str
    category: Optional[str]
    memory_type: str
    created_at: datetime
    updated_at: datetime


# ---------------------------------------------------------------- Pending actions (confirmation flow)


class PendingActionOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    id: int
    message_id: Optional[int]
    tool_name: str
    arguments: dict
    observations: list
    status: ActionStatus
    result: Optional[Any]
    error: Optional[str]
    created_at: datetime
    resolved_at: Optional[datetime]


class PendingActionCreate(BaseModel):
    message_id: Optional[int] = None
    tool_name: str = Field(min_length=1, max_length=128)
    arguments: dict = Field(default_factory=dict)
    observations: list = Field(default_factory=list)
    reply: Optional[str] = None


class ActionCompleteRequest(BaseModel):
    result: Optional[Any] = None


class ActionFailRequest(BaseModel):
    error: str


# ---------------------------------------------------------------- Sync


class SyncCompleteRequest(BaseModel):
    message_id: int
    response: str


class SyncFailRequest(BaseModel):
    message_id: int
    error: str


# ---------------------------------------------------------------- Agent / status


class HeartbeatOut(BaseModel):
    agent_name: str
    last_seen: datetime


class SystemStatusOut(BaseModel):
    pc_online: bool
    last_seen: Optional[datetime]
    pending_messages: int
    llm_provider: str
    llm_available: Optional[bool] = None
